import type { Product } from "@/context/cart-context";
import teddy from "@/assets/toy-teddy.jpg";
import doll from "@/assets/toy-doll.jpg";
import unicorn from "@/assets/toy-unicorn.jpg";
import fashionDoll from "@/assets/toy-fashion-doll.jpg";
import bunny from "@/assets/toy-bunny.jpg";
import kitchen from "@/assets/toy-kitchen.jpg";
import action from "@/assets/categories/action.jpg";
import animals from "@/assets/categories/animals.jpg";
import art from "@/assets/categories/art.jpg";
import baby from "@/assets/categories/baby.jpg";
import beach from "@/assets/categories/beach.jpg";
import building from "@/assets/categories/building.jpg";
import dollsCat from "@/assets/categories/dolls.jpg";
import educational from "@/assets/categories/educational.jpg";
import musical from "@/assets/categories/musical.jpg";
import plush from "@/assets/categories/plush.jpg";
import sports from "@/assets/categories/sports.jpg";
import vehicles from "@/assets/categories/vehicles.jpg";

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Cuddle Pink Teddy",
    description: "Super-soft pink teddy bear, perfect for hugs and naps.",
    price: 2999,
    image: teddy,
    rating: 5,
    category: "Plush Toys",
  },
  {
    id: "p2",
    name: "Sparkle Princess Doll",
    description: "Glittering tiara and a sparkly gown — magic in every twirl.",
    price: 4199,
    image: doll,
    rating: 5,
    category: "Dolls",
  },
  {
    id: "p3",
    name: "Rainbow Unicorn Plush",
    description: "A magical unicorn with a rainbow mane and shimmering horn.",
    price: 2700,
    image: unicorn,
    rating: 5,
    category: "Plush Toys",
  },
  {
    id: "p4",
    name: "Sweet Sunshine Doll",
    description: "A cheerful little doll with a heart and pink-bow buns.",
    price: 2399,
    image: fashionDoll,
    rating: 4,
    category: "Dolls",
  },
  {
    id: "p5",
    name: "Bow-Tie Bunny",
    description: "Fluffy white bunny with a darling pink ribbon bow.",
    price: 2160,
    image: bunny,
    rating: 5,
    category: "Plush Toys",
  },
  {
    id: "p6",
    name: "Dream Kitchen Set",
    description: "Pretend play kitchen with stove, sink and tiny utensils.",
    price: 5999,
    image: kitchen,
    rating: 5,
    category: "Educational",
  },
  {
    id: "p7",
    name: "Rainbow Building Blocks",
    description: "Colourful stacking blocks that spark endless creations.",
    price: 3599,
    image: building,
    rating: 5,
    category: "Building Blocks",
  },
  {
    id: "p8",
    name: "Mini Racer Cars",
    description: "A set of zippy die-cast cars ready for the race track.",
    price: 1980,
    image: vehicles,
    rating: 4,
    category: "Vehicles",
  },
  {
    id: "p9",
    name: "STEM Discovery Kit",
    description: "Hands-on science puzzles that make learning playful.",
    price: 5040,
    image: educational,
    rating: 5,
    category: "Educational",
  },
  {
    id: "p10",
    name: "Dollhouse Family Set",
    description: "A charming dollhouse with a sweet little family inside.",
    price: 6599,
    image: dollsCat,
    rating: 5,
    category: "Dolls",
  },
  {
    id: "p11",
    name: "Soft Cuddle Friends",
    description: "A basket of huggable plush pals in pastel shades.",
    price: 2520,
    image: plush,
    rating: 5,
    category: "Plush Toys",
  },
  {
    id: "p12",
    name: "Little Musician Set",
    description: "Tiny instruments for big first concerts at home.",
    price: 3300,
    image: musical,
    rating: 4,
    category: "Educational",
  },
  {
    id: "p13",
    name: "Hero Action Figures",
    description: "Poseable heroes ready for daring rescue missions.",
    price: 2880,
    image: action,
    rating: 4,
    category: "Action Figures",
  },
  {
    id: "p14",
    name: "Jungle Animal Friends",
    description: "A gentle herd of animal figures for imaginative safaris.",
    price: 2280,
    image: animals,
    rating: 5,
    category: "Animals",
  },
  {
    id: "p15",
    name: "Creative Art Studio",
    description: "Crayons, paints and paper for messy, happy afternoons.",
    price: 3840,
    image: art,
    rating: 5,
    category: "Educational",
  },
  {
    id: "p16",
    name: "Baby First Toys",
    description: "Soft rattles and teethers made for the tiniest hands.",
    price: 1799,
    image: baby,
    rating: 5,
    category: "Baby & Toddler",
  },
  {
    id: "p17",
    name: "Beach Play Bucket",
    description: "Bucket, spade and moulds for perfect sandcastles.",
    price: 1500,
    image: beach,
    rating: 4,
    category: "Beach & Water",
  },
  {
    id: "p18",
    name: "Outdoor Sports Pack",
    description: "Balls and rackets to keep little ones moving outside.",
    price: 5400,
    image: sports,
    rating: 4,
    category: "Sports & Outdoor",
  },

  /* ---------------- Trending Toys ---------------- */
  {
    id: "p19",
    name: "Glow Star Projector",
    description: "Fills the room with drifting stars at bedtime.",
    price: 3240,
    image: educational,
    rating: 5,
    category: "Educational",
    collection: "trending",
  },
  {
    id: "p20",
    name: "Bubble Pop Fidget",
    description: "Endless satisfying pops in rainbow silicone.",
    price: 1199,
    image: art,
    rating: 5,
    category: "Educational",
    collection: "trending",
  },
  {
    id: "p21",
    name: "Squishy Surprise Pack",
    description: "Six slow-rise squishies hidden in mystery pouches.",
    price: 1860,
    image: plush,
    rating: 4,
    category: "Plush Toys",
    collection: "trending",
  },
  {
    id: "p22",
    name: "Magnetic Tile Castle",
    description: "Click-together tiles for towers that really stand up.",
    price: 4799,
    image: building,
    rating: 5,
    category: "Building Blocks",
    collection: "trending",
  },
  {
    id: "p23",
    name: "Rainbow Slime Lab",
    description: "Mix, stretch and glitter your own slime batches.",
    price: 2250,
    image: art,
    rating: 4,
    category: "Educational",
    collection: "trending",
  },
  {
    id: "p24",
    name: "Pop-Up Play Tent",
    description: "A cosy hideaway that folds flat in seconds.",
    price: 4080,
    image: beach,
    rating: 5,
    category: "Beach & Water",
    collection: "trending",
  },

  /* ---------------- Drone Zone ---------------- */
  {
    id: "p25",
    name: "Mini Sky Drone",
    description: "Palm-sized quadcopter with one-touch take-off.",
    price: 5999,
    image: vehicles,
    rating: 5,
    category: "Vehicles",
    collection: "drones",
  },
  {
    id: "p26",
    name: "Camera Scout Drone",
    description: "Live HD view straight to your phone screen.",
    price: 10799,
    image: action,
    rating: 5,
    category: "Vehicles",
    collection: "drones",
  },
  {
    id: "p27",
    name: "Stunt Flip Drone",
    description: "360° barrel rolls at the tap of a button.",
    price: 7140,
    image: sports,
    rating: 4,
    category: "Vehicles",
    collection: "drones",
  },
  {
    id: "p28",
    name: "Glow Racing Drone",
    description: "LED arms that light up the whole flight path.",
    price: 7680,
    image: educational,
    rating: 4,
    category: "Vehicles",
    collection: "drones",
  },
  {
    id: "p29",
    name: "Hand-Control Flyer",
    description: "Hovers and follows your hand — no remote needed.",
    price: 3599,
    image: musical,
    rating: 4,
    category: "Vehicles",
    collection: "drones",
  },

  /* ---------------- Car Mania ---------------- */
  {
    id: "p30",
    name: "Turbo Race Track",
    description: "Loop-the-loop track with two turbo boosters.",
    price: 5399,
    image: vehicles,
    rating: 5,
    category: "Vehicles",
    collection: "cars",
  },
  {
    id: "p31",
    name: "Remote Rally Car",
    description: "Grippy tyres built for carpet and pavement alike.",
    price: 4560,
    image: action,
    rating: 5,
    category: "Vehicles",
    collection: "cars",
  },
  {
    id: "p32",
    name: "Monster Truck Duo",
    description: "Two chunky trucks that climb over anything.",
    price: 3300,
    image: sports,
    rating: 4,
    category: "Vehicles",
    collection: "cars",
  },
  {
    id: "p33",
    name: "Die-Cast Classics Set",
    description: "Five collectible metal cars with opening doors.",
    price: 2760,
    image: building,
    rating: 5,
    category: "Vehicles",
    collection: "cars",
  },
  {
    id: "p34",
    name: "City Garage Playset",
    description: "Ramps, a lift and a petrol pump for busy drivers.",
    price: 6240,
    image: educational,
    rating: 5,
    category: "Vehicles",
    collection: "cars",
  },

  /* ---------------- Little Princess ---------------- */
  {
    id: "p35",
    name: "Royal Tiara Set",
    description: "Sparkling tiara, wand and gloves for grand entrances.",
    price: 2399,
    image: doll,
    rating: 5,
    category: "Dolls",
    collection: "princess",
  },
  {
    id: "p36",
    name: "Ballgown Dress-Up Kit",
    description: "A twirl-worthy gown with satin ribbon ties.",
    price: 5100,
    image: fashionDoll,
    rating: 5,
    category: "Dolls",
    collection: "princess",
  },
  {
    id: "p37",
    name: "Princess Castle House",
    description: "Turrets, a balcony and tiny furniture inside.",
    price: 8160,
    image: dollsCat,
    rating: 5,
    category: "Dolls",
    collection: "princess",
  },
  {
    id: "p38",
    name: "Enchanted Tea Party",
    description: "Rose-print cups and saucers for royal guests.",
    price: 2880,
    image: kitchen,
    rating: 4,
    category: "Dolls",
    collection: "princess",
  },
  {
    id: "p39",
    name: "Unicorn Carriage",
    description: "A pastel carriage pulled by a glittering unicorn.",
    price: 4440,
    image: unicorn,
    rating: 5,
    category: "Dolls",
    collection: "princess",
  },

  /* ---------------- New Arrivals ---------------- */
  {
    id: "p40",
    name: "Wooden Balance Board",
    description: "Rock, bridge and slide — one board, many games.",
    price: 6960,
    image: sports,
    rating: 5,
    category: "Sports & Outdoor",
    collection: "new",
  },
  {
    id: "p41",
    name: "Soft Story Cubes",
    description: "Fabric blocks that tell a tale as you stack them.",
    price: 2580,
    image: baby,
    rating: 5,
    category: "Baby & Toddler",
    collection: "new",
  },
  {
    id: "p42",
    name: "Junior Keyboard",
    description: "Twenty-four keys and a built-in demo songbook.",
    price: 5520,
    image: musical,
    rating: 4,
    category: "Educational",
    collection: "new",
  },
  {
    id: "p43",
    name: "Safari Puzzle Mat",
    description: "Foam tiles that snap into a jungle play floor.",
    price: 3990,
    image: animals,
    rating: 5,
    category: "Animals",
    collection: "new",
  },
  {
    id: "p44",
    name: "Sketch & Trace Desk",
    description: "A light-up desk for tracing favourite drawings.",
    price: 4680,
    image: art,
    rating: 4,
    category: "Educational",
    collection: "new",
  },
  {
    id: "p45",
    name: "Cuddle Cloud Bear",
    description: "Extra-soft bear in a dreamy cloud-grey coat.",
    price: 3180,
    image: teddy,
    rating: 5,
    category: "Plush Toys",
    collection: "new",
  },
];

export const HOT_DEALS: Product[] = [
  {
    id: "hd1",
    name: "Stacks of squares",
    description: "Bright stacking squares that grow with every tower they build.",
    price: 700,
    image: building,
    rating: 5,
    category: "Building & Construction",
  },
  {
    id: "hd2",
    name: "Building block insects",
    description: "Snap-together bugs that teach shapes, colours and patience.",
    price: 2180,
    image: educational,
    rating: 5,
    category: "Educational Toys",
  },
  {
    id: "hd3",
    name: "Building block cars",
    description: "Buildable racers with chunky wheels made for little hands.",
    price: 270,
    image: vehicles,
    rating: 5,
    category: "Vehicles",
  },
  {
    id: "hd4",
    name: "Action block heroes",
    description: "Poseable block heroes ready for the next backyard adventure.",
    price: 270,
    image: action,
    rating: 5,
    category: "Action Toys",
  },
  {
    id: "hd5",
    name: "Building block flowers",
    description: "A blooming block garden that never needs watering.",
    price: 300,
    image: dollsCat,
    rating: 5,
    category: "Dolls & Accessories",
  },
  {
    id: "hd6",
    name: "Building block planes",
    description: "Cloud-hopping planes to build, fly and rebuild again.",
    price: 2960,
    image: plush,
    rating: 5,
    category: "Plush Toys",
  },
  {
    id: "hd7",
    name: "Musical block set",
    description: "Blocks that chime and rattle as the tower goes up.",
    price: 2190,
    image: musical,
    rating: 5,
    category: "Musical Instruments",
  },
  {
    id: "hd8",
    name: "Cartoon building blocks",
    description: "Friendly cartoon critters hiding inside every block set.",
    price: 290,
    image: animals,
    rating: 5,
    category: "Animals & Nature",
  },
];

export const POPULAR_TOYS: Product[] = [
  {
    id: "pt1",
    name: "Building Blocks Set",
    description: "A starter set of chunky blocks for endless tower building.",
    price: 700,
    image: building,
    rating: 5,
    category: "Building & Construction",
  },
  {
    id: "pt2",
    name: "Building Block Insects",
    description: "Build a whole bug collection, one colourful brick at a time.",
    price: 2180,
    image: educational,
    rating: 5,
    category: "Educational Toys",
  },
  {
    id: "pt3",
    name: "Building Block Cars",
    description: "Little racers to build, crash and rebuild all afternoon.",
    price: 270,
    image: vehicles,
    rating: 5,
    category: "Vehicles",
  },
  {
    id: "pt4",
    name: "Action Block Squad",
    description: "A squad of brick-built action figures with swappable parts.",
    price: 270,
    image: action,
    rating: 5,
    category: "Action Toys",
  },
  {
    id: "pt5",
    name: "Building Block Flowers",
    description: "A bouquet of bricks that stays in bloom all year.",
    price: 300,
    image: dollsCat,
    rating: 5,
    category: "Dolls & Accessories",
  },
  {
    id: "pt6",
    name: "Building Block Planes",
    description: "Jets and props to assemble and send soaring.",
    price: 2960,
    image: plush,
    rating: 5,
    category: "Plush Toys",
  },
  {
    id: "pt7",
    name: "Musical Block Band",
    description: "Blocks that pop, chime and drum as you stack them.",
    price: 2190,
    image: musical,
    rating: 5,
    category: "Musical Instruments",
  },
  {
    id: "pt8",
    name: "Cartoon Building Blocks",
    description: "Cheerful cartoon faces printed on soft-edged blocks.",
    price: 290,
    image: animals,
    rating: 5,
    category: "Animals & Nature",
  },
];

/** Every product that has a detail page, including homepage-only sections. */
export const ALL_PRODUCTS: Product[] = [...PRODUCTS, ...HOT_DEALS, ...POPULAR_TOYS];

export function findProductById(id: string) {
  return ALL_PRODUCTS.find((p) => p.id === id);
}

export type Collection = {
  slug: string;
  /** First half of the heading, rendered in solid text. */
  title: string;
  /** Second half, rendered with the pink→orange gradient. */
  highlight: string;
  eyebrow: string;
  subtitle: string;
};

export const COLLECTIONS: Collection[] = [
  {
    slug: "trending",
    title: "Trending",
    highlight: "Toy",
    eyebrow: "Hot Right Now",
    subtitle: "The toys everyone is asking for this week.",
  },
  {
    slug: "drones",
    title: "Drone",
    highlight: "Zone",
    eyebrow: "Take Flight",
    subtitle: "Little flyers with big adventures ahead.",
  },
  {
    slug: "cars",
    title: "Car",
    highlight: "Mania",
    eyebrow: "Start Your Engines",
    subtitle: "Racers, trucks and tracks for speed lovers.",
  },
  {
    slug: "princess",
    title: "Little",
    highlight: "Princess",
    eyebrow: "Once Upon A Time",
    subtitle: "Sparkle, twirl and reign over the playroom.",
  },
  {
    slug: "new",
    title: "New",
    highlight: "Arrivals",
    eyebrow: "Just Landed",
    subtitle: "Fresh off the shelf and ready to play.",
  },
];

export function getCollectionProducts(slug: string) {
  return PRODUCTS.filter((p) => p.collection === slug);
}
